### ISSUE TITLE
Thank you so much

### ISSUE THREAD

**Issue by zcxharrypotter** [ysc3839/Mi6-MIPay-Systemless#1]
It partly works on miui (global,stable) 10.0.1.0. Transport cards can be updated, but I can not add new nfc bank cards.

**Comment by ysc3839** [comment]
Currently this module uses files extracted from MIUI China Development. It may not work on MIUI Stable. I'll add a MIUI Stable version.

**Comment by ysc3839** [comment]
https://github.com/ysc3839/Mi6-MIPay-Systemless/releases/tag/v10.0.1.0-stable
Have a try!

**Comment by whyunzheng** [comment]
不是小米6手机，,刷了MIUI 8 GLOBAL7.2.21开发版， 可以刷这个包吗？具体是怎么刷的，谢谢

**Comment by ysc3839** [comment]
@whyunzheng MIUI 8 不可使用。
